export enum AppEnv {
  DEV = "develop",
  DEV_1 = "develop-one",
  DEV_2 = "develop-two",
  DEV_3 = "develop-three",
  DEV_4 = "develop-four",
  DEV_5 = "develop-five",
  DEV_6 = "develop-six",
  DEV_7 = "develop-seven",
  DEV_8 = "develop-eight",
  DEV_9 = "develop-nine",
  DEV_10 = "develop-ten",
  DEV_11 = "develop-eleven",
  EMPLOYEES_STG = "employees-stg",
  MY_PROD = "my-prod",
  MY_STG = "my-stg",
  PROD = "prod",
  SHOP_PROD = "shop-prod",
  SHOP_STG = "shop-stg",
  STG = "stg",
  TH_PROD = "th-prod",
  TH_STG = "th-stg",
  URUS_STG = "urus-stg",
  VN_PROD = "vn-prod",
  VN_STG = "vn-stg",
  PO_PROD = "po-prod",
}

export const envMap = {
  // dev
  [AppEnv.DEV]: {
    REACT_APP_API_BASE_URL: "https://api.dev.upmesh.io",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.dev.upmesh.io",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api.dev.upmesh.io",
    REACT_APP_AUTH0_CLIENT_ID: "KoRJdvtBTzPTxMx7Ls1aZ3z2EjT4Udy9",
    REACT_APP_AUTH0_DOMAIN: "upmesh-dev.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh-dev.us.auth0.com/api/v2/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.dev.upmesh.io",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.dev.upmesh.io/carts",
    REACT_APP_REGION: "sg",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "6F8ygMAcactymgaDf3qv0LsHtgPm2Cc6",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-3",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/sg/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "991728024979852",
    REACT_APP_GOOGLE_ANALYTICS: "F0TA87bgNMVxRcwSfv30rjBivUCHr5mH",
    REACT_APP_PATCH_NOTE_API: "https://staging-wordpress.upmesh.io",
  },
  [AppEnv.DEV_1]: {
    REACT_APP_API_BASE_URL: "https://api.devone.upmesh.io",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.devone.upmesh.io",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api.devone.upmesh.io",
    REACT_APP_AUTH0_CLIENT_ID: "KoRJdvtBTzPTxMx7Ls1aZ3z2EjT4Udy9",
    REACT_APP_AUTH0_DOMAIN: "upmesh-dev.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh-dev.us.auth0.com/api/v2/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.dev.upmesh.io",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.devone.upmesh.io/carts",
    REACT_APP_REGION: "my",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "6F8ygMAcactymgaDf3qv0LsHtgPm2Cc6",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-3",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/sg/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "991728024979852",
    REACT_APP_PATCH_NOTE_API: "https://staging-wordpress.upmesh.io",
  },
  [AppEnv.DEV_2]: {
    REACT_APP_API_BASE_URL: "https://api.devtwo.upmesh.io",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.devtwo.upmesh.io",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api.devtwo.upmesh.io",
    REACT_APP_AUTH0_CLIENT_ID: "KoRJdvtBTzPTxMx7Ls1aZ3z2EjT4Udy9",
    REACT_APP_AUTH0_DOMAIN: "upmesh-dev.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh-dev.us.auth0.com/api/v2/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.devtwo.upmesh.io",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.devtwo.upmesh.io/carts",
    REACT_APP_REGION: "th",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "6F8ygMAcactymgaDf3qv0LsHtgPm2Cc6",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-3",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/sg/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "991728024979852",
    REACT_APP_PATCH_NOTE_API: "https://staging-wordpress.upmesh.io",
  },
  [AppEnv.DEV_3]: {
    REACT_APP_API_BASE_URL: "https://api.devthree.upmesh.io",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.devthree.upmesh.io",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api.devthree.upmesh.io",
    REACT_APP_AUTH0_CLIENT_ID: "Eui9QtZ1yqm0drpY9mHKS2fJ7l3SIMl7",
    REACT_APP_AUTH0_DOMAIN: "upmesh-dev.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh-dev.us.auth0.com/api/v2/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.devthree.upmesh.io",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.devthree.upmesh.io/carts",
    REACT_APP_REGION: "sg",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "hsepD01RqSwEJa4fbKJNTWn2sCXLv59T",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-3",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/sg/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "705725053331928",
    REACT_APP_PATCH_NOTE_API: "https://staging-wordpress.upmesh.io",
  },
  [AppEnv.DEV_4]: {
    REACT_APP_API_BASE_URL: "https://api.devfour.upmesh.io",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.devfour.upmesh.io",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api.devfour.upmesh.io",
    REACT_APP_AUTH0_CLIENT_ID: "sYJOVwKzhWx6qJxwbeEtJQVh7LKBxKfb",
    REACT_APP_AUTH0_DOMAIN: "upmesh-dev.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh-dev.us.auth0.com/api/v2/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.devfour.upmesh.io",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.devfour.upmesh.io/carts",
    REACT_APP_REGION: "sg",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "6F8ygMAcactymgaDf3qv0LsHtgPm2Cc6",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-3",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/sg/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "705725053331928",
    REACT_APP_PATCH_NOTE_API: "https://staging-wordpress.upmesh.io",
  },
  [AppEnv.DEV_5]: {
    REACT_APP_API_BASE_URL: "https://api.devfive.upmesh.io",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.devfive.upmesh.io",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api.devfive.upmesh.io",
    REACT_APP_AUTH0_CLIENT_ID: "KoRJdvtBTzPTxMx7Ls1aZ3z2EjT4Udy9",
    REACT_APP_AUTH0_DOMAIN: "upmesh-dev.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh-dev.us.auth0.com/api/v2/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.devfive.upmesh.io",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.devfive.upmesh.io/carts",
    REACT_APP_REGION: "sg",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "6F8ygMAcactymgaDf3qv0LsHtgPm2Cc6",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-3",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/sg/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "991728024979852",
    REACT_APP_PATCH_NOTE_API: "https://staging-wordpress.upmesh.io",
  },
  [AppEnv.DEV_6]: {
    REACT_APP_API_BASE_URL: "https://api.devsix.upmesh.io",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.devsix.upmesh.io",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api.devsix.upmesh.io",
    REACT_APP_AUTH0_CLIENT_ID: "KoRJdvtBTzPTxMx7Ls1aZ3z2EjT4Udy9",
    REACT_APP_AUTH0_DOMAIN: "upmesh-dev.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh-dev.us.auth0.com/api/v2/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.devsix.upmesh.io",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.devsix.upmesh.io/carts",
    REACT_APP_REGION: "sg",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "6F8ygMAcactymgaDf3qv0LsHtgPm2Cc6",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-3",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/sg/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "991728024979852",
    REACT_APP_PATCH_NOTE_API: "https://staging-wordpress.upmesh.io",
  },
  [AppEnv.DEV_7]: {
    REACT_APP_API_BASE_URL: "https://api.devseven.upmesh.io",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.devseven.upmesh.io",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api.devseven.upmesh.io",
    REACT_APP_AUTH0_CLIENT_ID: "KoRJdvtBTzPTxMx7Ls1aZ3z2EjT4Udy9",
    REACT_APP_AUTH0_DOMAIN: "upmesh-dev.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh-dev.us.auth0.com/api/v2/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.devseven.upmesh.io",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.devseven.upmesh.io/carts",
    REACT_APP_REGION: "sg",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "6F8ygMAcactymgaDf3qv0LsHtgPm2Cc6",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-3",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/sg/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "991728024979852",
    REACT_APP_PATCH_NOTE_API: "https://staging-wordpress.upmesh.io",
  },
  [AppEnv.DEV_8]: {
    REACT_APP_API_BASE_URL: "https://api.deveight.upmesh.io",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.deveight.upmesh.io",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api.deveight.upmesh.io",
    REACT_APP_AUTH0_CLIENT_ID: "sYJOVwKzhWx6qJxwbeEtJQVh7LKBxKfb",
    REACT_APP_AUTH0_DOMAIN: "upmesh-dev.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh-dev.us.auth0.com/api/v2/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.deveight.upmesh.io",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.deveight.upmesh.io/carts",
    REACT_APP_REGION: "sg",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "6F8ygMAcactymgaDf3qv0LsHtgPm2Cc6",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-3",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/sg/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "991728024979852",
    REACT_APP_PATCH_NOTE_API: "https://staging-wordpress.upmesh.io",
  },
  [AppEnv.DEV_9]: {
    REACT_APP_API_BASE_URL: "https://api.devnine.upmesh.io",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.devnine.upmesh.io",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api.devnine.upmesh.io",
    REACT_APP_AUTH0_CLIENT_ID: "sYJOVwKzhWx6qJxwbeEtJQVh7LKBxKfb",
    REACT_APP_AUTH0_DOMAIN: "upmesh-dev.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh-dev.us.auth0.com/api/v2/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.devnine.upmesh.io",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.devnine.upmesh.io/carts",
    REACT_APP_REGION: "sg",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "6F8ygMAcactymgaDf3qv0LsHtgPm2Cc6",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-3",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/sg/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "991728024979852",
    REACT_APP_PATCH_NOTE_API: "https://staging-wordpress.upmesh.io",
  },
  [AppEnv.DEV_10]: {
    REACT_APP_API_BASE_URL: "https://api.devten.upmesh.io",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.devten.upmesh.io",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api.devten.upmesh.io",
    REACT_APP_AUTH0_CLIENT_ID: "KoRJdvtBTzPTxMx7Ls1aZ3z2EjT4Udy9",
    REACT_APP_AUTH0_DOMAIN: "upmesh-dev.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh-dev.us.auth0.com/api/v2/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.devten.upmesh.io",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.devten.upmesh.io/carts",
    REACT_APP_REGION: "th",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "6F8ygMAcactymgaDf3qv0LsHtgPm2Cc6",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-3",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/sg/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "991728024979852",
    REACT_APP_PATCH_NOTE_API: "https://staging-wordpress.upmesh.io",
  },
  [AppEnv.DEV_11]: {
    REACT_APP_API_BASE_URL: "https://api.develeven.upmesh.io",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.develeven.upmesh.io",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api.develeven.upmesh.io",
    REACT_APP_AUTH0_CLIENT_ID: "KoRJdvtBTzPTxMx7Ls1aZ3z2EjT4Udy9",
    REACT_APP_AUTH0_DOMAIN: "upmesh-dev.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh-dev.us.auth0.com/api/v2/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.develeven.upmesh.io",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.develeven.upmesh.io/carts",
    REACT_APP_REGION: "th",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "6F8ygMAcactymgaDf3qv0LsHtgPm2Cc6",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-3",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/sg/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "991728024979852",
    REACT_APP_PATCH_NOTE_API: "https://staging-wordpress.upmesh.io",
  },
  // staging
  [AppEnv.STG]: {
    REACT_APP_API_BASE_URL: "https://api.stg.upmesh.io",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.stg.upmesh.io",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api.stg.upmesh.io",
    REACT_APP_AUTH0_CLIENT_ID: "Eui9QtZ1yqm0drpY9mHKS2fJ7l3SIMl7",
    REACT_APP_AUTH0_DOMAIN: "upmesh.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh.io/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.stg.upmesh.io",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.stg.upmesh.io/carts",
    REACT_APP_REGION: "sg",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "hsepD01RqSwEJa4fbKJNTWn2sCXLv59T",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-2",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/sg/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "705725053331928",
    REACT_APP_SENTRY_DSN:
      "https://f84f4c369cc7491e9b28abcf6d5533e8@o1276801.ingest.sentry.io/6474536",
    REACT_APP_SENTRY_ENV: "stg-sg",
    REACT_APP_PATCH_NOTE_API: "https://wordpress.upmesh.io",
  },
  [AppEnv.EMPLOYEES_STG]: {
    REACT_APP_API_BASE_URL: "https://api.employees.upmesh.io",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.employees.upmesh.io",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api.employees.upmesh.io",
    REACT_APP_AUTH0_CLIENT_ID: "Eui9QtZ1yqm0drpY9mHKS2fJ7l3SIMl7",
    REACT_APP_AUTH0_DOMAIN: "upmesh.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh.io/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.employees.upmesh.io",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.employees.upmesh.io/carts",
    REACT_APP_REGION: "sg",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "hsepD01RqSwEJa4fbKJNTWn2sCXLv59T",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-2",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/sg/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "705725053331928",
    REACT_APP_PATCH_NOTE_API: "https://wordpress.upmesh.io",
  },
  [AppEnv.MY_STG]: {
    REACT_APP_API_BASE_URL: "https://api.stg.upmesh.my",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.stg.upmesh.my",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api.stg.upmesh.my",
    REACT_APP_AUTH0_CLIENT_ID: "Eui9QtZ1yqm0drpY9mHKS2fJ7l3SIMl7",
    REACT_APP_AUTH0_DOMAIN: "upmesh.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh.io/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.stg.upmesh.my",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.stg.upmesh.my/carts",
    REACT_APP_REGION: "my",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "hsepD01RqSwEJa4fbKJNTWn2sCXLv59T",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-3",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/my/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "705725053331928",
    REACT_APP_SENTRY_DSN:
      "https://f84f4c369cc7491e9b28abcf6d5533e8@o1276801.ingest.sentry.io/6474536",
    REACT_APP_SENTRY_ENV: "stg-my",
    REACT_APP_PATCH_NOTE_API: "https://wordpress.upmesh.io",
  },
  [AppEnv.SHOP_STG]: {
    REACT_APP_API_BASE_URL: "https://api.stg.upmesh.shop",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.stg.upmesh.shop",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api.stg.upmesh.shop",
    REACT_APP_AUTH0_CLIENT_ID: "Eui9QtZ1yqm0drpY9mHKS2fJ7l3SIMl7",
    REACT_APP_AUTH0_DOMAIN: "upmesh.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh.io/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.stg.upmesh.shop",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.stg.upmesh.shop/carts",
    REACT_APP_REGION: "ph",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "hsepD01RqSwEJa4fbKJNTWn2sCXLv59T",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-5",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/ph/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "705725053331928",
    REACT_APP_GOOGLE_ANALYTICS: "F0TA87bgNMVxRcwSfv30rjBivUCHr5mH",
    REACT_APP_SENTRY_DSN:
      "https://f84f4c369cc7491e9b28abcf6d5533e8@o1276801.ingest.sentry.io/6474536",
    REACT_APP_SENTRY_ENV: "stg-shop",
    REACT_APP_PATCH_NOTE_API: "https://wordpress.upmesh.io",
  },
  [AppEnv.TH_STG]: {
    REACT_APP_API_BASE_URL: "https://api-th.stg.upmesh.io",
    REACT_APP_API_BASE_SEARCH_URL: "https://search-th.stg.upmesh.io",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api-th.stg.upmesh.io",
    REACT_APP_AUTH0_CLIENT_ID: "Eui9QtZ1yqm0drpY9mHKS2fJ7l3SIMl7",
    REACT_APP_AUTH0_DOMAIN: "upmesh.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh.io/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout-th.stg.upmesh.io",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer-th.stg.upmesh.io/carts",
    REACT_APP_REGION: "th",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "hsepD01RqSwEJa4fbKJNTWn2sCXLv59T",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-2",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/th/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "705725053331928",
    REACT_APP_SENTRY_DSN:
      "https://f84f4c369cc7491e9b28abcf6d5533e8@o1276801.ingest.sentry.io/6474536",
    REACT_APP_SENTRY_ENV: "stg-th",
    REACT_APP_PATCH_NOTE_API: "https://wordpress.upmesh.io",
  },
  [AppEnv.URUS_STG]: {
    REACT_APP_API_BASE_URL: "https://api-urus.stg.upmesh.io",
    REACT_APP_AUTH0_CLIENT_ID: "Eui9QtZ1yqm0drpY9mHKS2fJ7l3SIMl7",
    REACT_APP_AUTH0_DOMAIN: "upmesh.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh.io/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout-urus.stg.upmesh.io",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer-urus.stg.upmesh.io/carts",
    REACT_APP_REGION: "th",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "hsepD01RqSwEJa4fbKJNTWn2sCXLv59T",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-2",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/th/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "705725053331928",
    REACT_APP_PATCH_NOTE_API: "https://staging-wordpress.upmesh.io",
  },
  [AppEnv.VN_STG]: {
    REACT_APP_API_BASE_URL: "https://api.stg.upmesh.vn",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.stg.upmesh.vn",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api.stg.upmesh.vn",
    REACT_APP_AUTH0_CLIENT_ID: "Eui9QtZ1yqm0drpY9mHKS2fJ7l3SIMl7",
    REACT_APP_AUTH0_DOMAIN: "upmesh.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh.io/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.stg.upmesh.vn",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.stg.upmesh.vn/carts",
    REACT_APP_REGION: "vn",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "hsepD01RqSwEJa4fbKJNTWn2sCXLv59T",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-3",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/vn/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "705725053331928",
    REACT_APP_SENTRY_DSN:
      "https://f84f4c369cc7491e9b28abcf6d5533e8@o1276801.ingest.sentry.io/6474536",
    REACT_APP_SENTRY_ENV: "stg-vn",
    REACT_APP_PATCH_NOTE_API: "https://wordpress.upmesh.io",
  },

  // prod
  [AppEnv.PROD]: {
    REACT_APP_API_BASE_URL: "https://api.upmesh.io",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.upmesh.io",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://notify.upmesh.io",
    REACT_APP_AUTH0_CLIENT_ID: "Eui9QtZ1yqm0drpY9mHKS2fJ7l3SIMl7",
    REACT_APP_AUTH0_DOMAIN: "upmesh.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh.io/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.upmesh.io",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.upmesh.io/carts",
    REACT_APP_REGION: "sg",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "hsepD01RqSwEJa4fbKJNTWn2sCXLv59T",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-1",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/sg/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "705725053331928",
    REACT_APP_GOOGLE_ANALYTICS: "7oxInTlml8vnRLr0fo75UL9xistc2F6k",
    REACT_APP_SENTRY_DSN:
      "https://f84f4c369cc7491e9b28abcf6d5533e8@o1276801.ingest.sentry.io/6474536",
    REACT_APP_SENTRY_ENV: "prod-sg",
    REACT_APP_PATCH_NOTE_API: "https://wordpress.upmesh.io",
  },
  [AppEnv.MY_PROD]: {
    REACT_APP_API_BASE_URL: "https://api.upmesh.my",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.upmesh.my",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api.upmesh.my",
    REACT_APP_AUTH0_CLIENT_ID: "Eui9QtZ1yqm0drpY9mHKS2fJ7l3SIMl7",
    REACT_APP_AUTH0_DOMAIN: "upmesh.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh.io/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.upmesh.my",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.upmesh.my/carts",
    REACT_APP_REGION: "my",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "hsepD01RqSwEJa4fbKJNTWn2sCXLv59T",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-1",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/my/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "705725053331928",
    REACT_APP_GOOGLE_ANALYTICS: "mEbGBJTMEFYE0RBIts7JmGVPJVRJUFIc",
    REACT_APP_SENTRY_DSN:
      "https://f84f4c369cc7491e9b28abcf6d5533e8@o1276801.ingest.sentry.io/6474536",
    REACT_APP_SENTRY_ENV: "prod-my",
    REACT_APP_PATCH_NOTE_API: "https://wordpress.upmesh.io",
  },
  [AppEnv.PO_PROD]: {
    REACT_APP_API_BASE_URL: "https://api-po.upmesh.io",
    REACT_APP_API_BASE_SEARCH_URL: "https://search-po.upmesh.io",
    REACT_APP_AUTH0_CLIENT_ID: "Eui9QtZ1yqm0drpY9mHKS2fJ7l3SIMl7",
    REACT_APP_AUTH0_DOMAIN: "upmesh.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh.io/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout-po.upmesh.io",
    REACT_APP_REGION: "sg",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "hsepD01RqSwEJa4fbKJNTWn2sCXLv59T",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-4",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/sg/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "705725053331928",
    REACT_APP_PATCH_NOTE_API: "https://wordpress.upmesh.io",
  },
  [AppEnv.SHOP_PROD]: {
    REACT_APP_API_BASE_URL: "https://api.upmesh.shop",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.upmesh.shop",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api.upmesh.shop",
    REACT_APP_AUTH0_CLIENT_ID: "Eui9QtZ1yqm0drpY9mHKS2fJ7l3SIMl7",
    REACT_APP_AUTH0_DOMAIN: "upmesh.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh.io/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.upmesh.shop",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.upmesh.shop/carts",
    REACT_APP_REGION: "ph",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "hsepD01RqSwEJa4fbKJNTWn2sCXLv59T",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-4",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/ph/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "705725053331928",
    REACT_APP_GOOGLE_ANALYTICS: "iMUqghVOIL9ZRUYctdT0C1bluuyiZDuY",
    REACT_APP_SENTRY_DSN:
      "https://f84f4c369cc7491e9b28abcf6d5533e8@o1276801.ingest.sentry.io/6474536",
    REACT_APP_SENTRY_ENV: "prod-shop",
    REACT_APP_PATCH_NOTE_API: "https://wordpress.upmesh.io",
  },
  [AppEnv.TH_PROD]: {
    REACT_APP_API_BASE_URL: "https://api-th.upmesh.io",
    REACT_APP_API_BASE_SEARCH_URL: "https://search-th.upmesh.io",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api-th.upmesh.io",
    REACT_APP_AUTH0_CLIENT_ID: "Eui9QtZ1yqm0drpY9mHKS2fJ7l3SIMl7",
    REACT_APP_AUTH0_DOMAIN: "upmesh.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh.io/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout-th.upmesh.io",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer-th.upmesh.io/carts",
    REACT_APP_REGION: "th",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "hsepD01RqSwEJa4fbKJNTWn2sCXLv59T",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-1",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/th/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "705725053331928",
    REACT_APP_GOOGLE_ANALYTICS: "pkkfMvPcObPVKcLH1CGfnsSgZBq2PIcv",
    REACT_APP_SENTRY_DSN:
      "https://f84f4c369cc7491e9b28abcf6d5533e8@o1276801.ingest.sentry.io/6474536",
    REACT_APP_SENTRY_ENV: "prod-th",
    REACT_APP_PATCH_NOTE_API: "https://wordpress.upmesh.io",
  },
  [AppEnv.VN_PROD]: {
    REACT_APP_API_BASE_URL: "https://api.upmesh.vn",
    REACT_APP_API_BASE_SEARCH_URL: "https://search.upmesh.vn",
    REACT_APP_API_NOTIFY_SYSTEM_BASE_URL: "https://api.upmesh.vn",
    REACT_APP_AUTH0_CLIENT_ID: "Eui9QtZ1yqm0drpY9mHKS2fJ7l3SIMl7",
    REACT_APP_AUTH0_DOMAIN: "upmesh.us.auth0.com",
    REACT_APP_AUTH0_AUDIENCE: "https://upmesh.io/",
    REACT_APP_CHECKOUT_BASE_URL: "https://checkout.upmesh.vn",
    REACT_APP_CHECKOUT_BASE_URL_NEW: "https://buyer.upmesh.vn/carts",
    REACT_APP_REGION: "vn",
    REACT_APP_AUTH0_SUBADMIN_CLIENT_ID: "hsepD01RqSwEJa4fbKJNTWn2sCXLv59T",
    REACT_APP_GA_TRACKING_CODE: "UA-199894002-1",
    REACT_APP_PRIVACY_POLICY_URL: "https://upmesh.io/vn/privacy",
    REACT_APP_CLIENT_ACCESS_TOKEN: "705725053331928",
    REACT_APP_GOOGLE_ANALYTICS: "mEbGBJTMEFYE0RBIts7JmGVPJVRJUFIc",
    REACT_APP_SENTRY_DSN:
      "https://f84f4c369cc7491e9b28abcf6d5533e8@o1276801.ingest.sentry.io/6474536",
    REACT_APP_SENTRY_ENV: "prod-vn",
    REACT_APP_PATCH_NOTE_API: "https://wordpress.upmesh.io",
  },
};

export type Enviromnent = typeof envMap["prod"];

export default envMap[process.env.APP_ENV as AppEnv.DEV];
